### ISSUE TITLE
Loading of new lod hangs when going lod1.2 --> lod2.2

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/3dbag-viewer#46]
https://godzilla.bk.tudelft.nl/3dbag-viewer/#/en/viewer?rdx=98900.0950637635&rdy=441408.397495486&ox=-2246.234100099122&oy=2827.808289596649&oz=-1852.5566103218516 

This is what it looks like if I don't navigate the map:

![image](https://user-images.githubusercontent.com/7190603/108842370-779c0a00-75d9-11eb-8d0b-9aa37effed43.png)

After I zoom in-out a couple times, it loads correctly.

**Comment by jliempt** [comment]
This is due to the test with the new quadtree tileset (currently only done for LoD 2.2). It has a different bounding box than the old tilesets and thus a different `"transform"`. The basemap tiles rely on this so they get messed up when it's changed.

So this will be resolved when we export all LoDs with the same tileset.
